# Generated by Django 5.0.1 on 2024-01-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countertable',
            name='last_Appoinment_id',
            field=models.IntegerField(default=0),
        ),
    ]
