# Generated by Django 5.0.1 on 2024-01-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_countertable_last_appoinment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_Appoinment_id', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='countertable',
            name='last_Appoinment_id',
        ),
    ]
