# Generated by Django 5.0.1 on 2024-01-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_counterclass_remove_countertable_last_appoinment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterClass',
        ),
        migrations.AddField(
            model_name='countertable',
            name='last_appoinment_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countertable',
            name='last_payment_entry_id',
            field=models.IntegerField(default=0),
        ),
    ]
