# Generated by Django 5.0.1 on 2024-02-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_delete_counterclass_countertable_last_appoinment_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterTable',
        ),
    ]
