# Generated by Django 5.0.1 on 2024-02-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0005_delete_countertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_staff_id', models.IntegerField(default=0)),
                ('last_appoinment_id', models.IntegerField(default=0)),
                ('last_payment_entry_id', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
