# Generated by Django 5.0.1 on 2024-01-31 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinments',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Appoinment_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('total_payment', models.FloatField()),
                ('appoinments_status', models.CharField(blank=True, choices=[('Pending', 'Task Pending'), ('Ongoing', 'Task On-Going'), ('Done', 'Task Done')], default='Pending', max_length=50)),
                ('paid_payment', models.FloatField(blank=True, default=0)),
                ('remaining_payment', models.FloatField(blank=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Payment Pending'), ('Done', 'Payment Done'), ('Partially Paid', 'Partially Paid')], default='Pending', max_length=50)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
