# Generated by Django 5.0.1 on 2024-01-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_appoinments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinments',
            name='appoinments_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Appoinment Pending'), ('Ongoing', 'Appoinment On-Going'), ('Done', 'Appoinment Done')], default='Pending', max_length=50),
        ),
    ]
