# Generated by Django 5.0.1 on 2024-01-31 10:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0003_alter_appoinments_appoinments_status'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('report_charge', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='appoinment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appoinment_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('total_payment', models.FloatField()),
                ('appoinment_status', models.CharField(blank=True, choices=[('Pending', 'appoinment Pending'), ('Ongoing', 'appoinment On-Going'), ('Done', 'appoinment Done')], default='Pending', max_length=50)),
                ('paid_payment', models.FloatField(blank=True, default=0)),
                ('remaining_payment', models.FloatField(blank=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Payment Pending'), ('Done', 'Payment Done'), ('Partially Paid', 'Partially Paid')], default='Pending', max_length=50)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='payment_installment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('payment_entry', models.FloatField(default=0)),
                ('paid_date', models.DateField(default=datetime.date(2024, 1, 31))),
                ('appoinment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appoinment')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffregister')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='report_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.reporttype'),
        ),
        migrations.DeleteModel(
            name='Appoinments',
        ),
    ]
