# Generated by Django 5.0.1 on 2024-01-31 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_reporttype_appoinment_payment_installment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='report_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='patient.reporttype'),
        ),
    ]
