# Generated by Django 5.0.1 on 2024-01-31 11:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_reporttype_rename_doctor_id_appoinment_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='report_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.reporttype'),
        ),
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 11, 32, 2, 186479, tzinfo=datetime.timezone.utc)),
        ),
    ]
