# Generated by Django 5.0.1 on 2024-02-02 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_patient_report_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_installment',
            name='appoinment_id',
        ),
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 5, 38, 6, 700755, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='appoinment',
        ),
    ]
