# Generated by Django 5.0.1 on 2024-02-02 05:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0012_remove_payment_installment_appoinment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 5, 59, 52, 731298, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='appoinment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appoinment_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('total_payment', models.FloatField()),
                ('appoinment_status', models.CharField(blank=True, choices=[('Pending', 'appoinment Pending'), ('Ongoing', 'appoinment On-Going'), ('Done', 'appoinment Done')], default='Pending', max_length=50)),
                ('paid_payment', models.FloatField(blank=True, default=0)),
                ('remaining_payment', models.FloatField(blank=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Payment Pending'), ('Done', 'Payment Done'), ('Partially Paid', 'Partially Paid')], default='Pending', max_length=50)),
                ('patients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment_installment',
            name='appoinment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.appoinment'),
        ),
    ]
