# Generated by Django 5.0.1 on 2024-02-02 06:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_payment_installment_paid_date_appoinment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='patient',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.reporttype'),
        ),
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 6, 6, 3, 242627, tzinfo=datetime.timezone.utc)),
        ),
    ]
