# Generated by Django 5.0.1 on 2024-02-02 06:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_remove_patient_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_installment',
            name='appoinment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appoinment'),
        ),
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 6, 25, 40, 835080, tzinfo=datetime.timezone.utc)),
        ),
    ]
