# Generated by Django 5.0.1 on 2024-02-02 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_payment_installment_appoinment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 6, 34, 52, 249294, tzinfo=datetime.timezone.utc)),
        ),
    ]
