# Generated by Django 5.0.1 on 2024-02-05 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_alter_payment_installment_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 13, 42, 43, 742158, tzinfo=datetime.timezone.utc)),
        ),
    ]
