# Generated by Django 5.0.1 on 2024-02-05 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_alter_payment_installment_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='appoinment_status',
        ),
        migrations.RemoveField(
            model_name='appoinment',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 13, 43, 49, 589667, tzinfo=datetime.timezone.utc)),
        ),
    ]
