# Generated by Django 5.0.1 on 2024-02-05 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_remove_appoinment_appoinment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_installment',
            name='appoinment_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='payment_installment',
            name='payment_entry',
        ),
        migrations.RemoveField(
            model_name='payment_installment',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AddField(
            model_name='payment_installment',
            name='paid_payment',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment_installment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='appoinment',
        ),
    ]
