# Generated by Django 5.0.1 on 2024-02-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0022_patient_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
