# Generated by Django 5.0.1 on 2024-02-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_alter_patient_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='report_type',
        ),
        migrations.DeleteModel(
            name='payment_installment',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='ReportType',
        ),
    ]
