# Generated by Django 5.0.1 on 2024-02-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0024_remove_patient_doctor_id_remove_patient_report_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
